version: "3"

services:
  ##########################################
  # There's a lot going on in this file; it's normal to get lost with all the
  # options and variables
  #
  # Before diving in, make sure to take a look at the documentation.  In
  # particular, it will be helpful to read the components-overview section
  # (https://games-on-whales.github.io/gow/components-overview.html)
  # in order to get a view on how the various components are tied together.
  ###################

  ####################
  # Sunshine is the heart of the streaming setup; it takes your desktop and
  # encodes it for delivery over the network
  sunshine:
  # build:
  #   context: ./images/
  #   dockerfile: sunshine/Dockerfile
  # Uncomment the following to override the default sunshine version
  #   args:
  #     BUILD_TYPE: RELEASE
  #     SUNSHINE_SHA: d9f79527104694a223eb9d64309e9337f46909d6
    image: ghcr.io/games-on-whales/sunshine:edge
    runtime: ${DOCKER_RUNTIME}
    ports:
      - 47984-47990:47984-47990/tcp
      - 48010:48010
      - 47998-48000:47998-48000/udp
    privileged: true
    volumes:
      # Xorg socket in order to get the screen
      - ${XORG_SOCKET}:/tmp/.X11-unix
      # Pulse socket, audio
      - ${PULSE_SOCKET_HOST}:${PULSE_SOCKET_GUEST}
      # Home directory: sunshine state + configs
      - ${local_state}/:/home/retro/
      # OPTIONAL: host dbus used by avahi in order to publish Sunshine for auto network discovery
      - ${DBUS}:/run/dbus:ro
    ipc: ${SHARED_IPC}  # Needed for MIT-SHM, removing this should cause a performance hit see https://github.com/jessfraz/dockerfiles/issues/359

    env_file:
      - config/common.env
      - config/xorg.env
      # run-gow: gpu_env

    environment:
      LOG_LEVEL: ${SUNSHINE_LOG_LEVEL}
      GOW_REQUIRED_DEVICES: /dev/uinput /dev/input/event* /dev/dri/*
      # Username and password for the web-ui at https://xxx.xxx.xxx.xxx:47990
      SUNSHINE_USER: ${SUNSHINE_USER}
      SUNSHINE_PASS: ${SUNSHINE_PASS}
      XDG_RUNTIME_DIR: /tmp/.X11-unix
