title: Games on Whales
tagline: Stream games (and GUI) running on Docker with HW acceleration and low latency!
description: GOW let's you stream games (and GUI) running on Docker with HW acceleration and low latency!
url: "//games-on-whales.github.io"
baseurl: "gow/" # the subpath of your site, e.g. /blog

# Build settings
remote_theme: pmarsceill/just-the-docs

# just-the-docs settings
search_enabled: true
aux_links:
  "GitHub":
    - "//github.com/games-on-whales/gow"
aux_links_new_tab: false
color_scheme: gow-dark

collections_dir: collections
collections:
  overview:
    permalink: "/:collection/:path/"
    output: true
  configuration:
    permalink: "/:collection/:path/"
    output: true
  installation:
    permalink: "/:collection/:path/"
    output: true
  contributing:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    overview:
      name: What is GOW?
    installation:
      name: Installation
    configuration:
      name: Configuration
    contributing:
      name: Contributing/Developing
