name: docker_build

on:
  push:
  pull_request: #They will only build the containers, not push them
    types:
      - opened
      - reopened
  schedule:
    - cron: "0 0 * * *" #nightly
  workflow_dispatch:

jobs:
  base:
    uses: ./.github/workflows/docker-build-and-publish.yml
    with:
      image_name: "base"
    secrets: inherit

  base-app:
    needs: [ base ]
    uses: ./.github/workflows/docker-build-and-publish.yml
    with:
      image_name: "base-app"
    secrets: inherit

  apps:
    needs: [ base, base-app ]
    strategy:
      matrix:
        image:
        - { name: xorg,       platforms: "linux/amd64,linux/arm64" }
        - { name: pulseaudio, platforms: "linux/amd64,linux/arm64" }
        - { name: udevd,      platforms: "linux/amd64,linux/arm64" }
        - { name: sunshine,   platforms: "linux/amd64" }
        - { name: retroarch,  platforms: "linux/amd64,linux/arm64" }
        - { name: steam,      platforms: "linux/amd64"             }
      fail-fast: false
    uses: ./.github/workflows/docker-build-and-publish.yml
    with:
      image_name: "${{ matrix.image.name }}"
      platforms: "${{ matrix.image.platforms }}"
    secrets: inherit

