name: Run linters

on: [ pull_request ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Shell scripts
        uses: reviewdog/action-shellcheck@v1
        with:
          reporter: github-pr-review
          check_all_files_with_shebangs: "true"
          filter_mode: nofilter

      - name: Dockerfiles
        uses: reviewdog/action-hadolint@v1
        with:
          reporter: github-pr-review
          # at least for now, ignore suggestions to pin specific versions of
          # apt packages.
          hadolint_ignore: DL3008
          filter_mode: nofilter

